import type { SetTime } from './schedule';

// Song pools are generated by scripts/build-song-pools.mjs; data/README.md documents the format.
// songs/<year>.json maps each band (keyed by the exact schedule `band` string) to a weighted pool
// of up to six songs. A band missing from a year's file has no song data for that year.

export type SongRole = 'classic' | 'era' | 'both' | 'filler';

export type PoolSong = {
  title: string;
  /** Set only when the artist name differs from the band key (spelling or case). */
  artist?: string;
  /** First release year. */
  year: number;
  role: SongRole;
  /** Relative chance of being drawn, comparable only within one pool. */
  weight: number;
};

export type BandSongs = {
  mbid: string;
  confidence: 'high' | 'low';
  /** "Title (year)" of the album promoted for this tour year, or null. */
  currentAlbum: string | null;
  flags?: Array<'released-after-tour'>;
  pool: PoolSong[];
};

export type YearSongs = {
  schemaVersion: 1;
  year: number;
  generatedAt: string;
  params: Record<string, unknown>;
  bands: Record<string, BandSongs>;
};

export type PlaylistTrack = { band: string; artist: string; title: string; year: number };

export type Playlist = {
  year: number;
  tracks: PlaylistTrack[];
  /** Picked bands that have no song data for this year. */
  noSongs: string[];
};

// Lazy, like the schedules: a year's file is only fetched when a playlist is built for it.
const songLoaders = import.meta.glob<YearSongs>('./songs/*.json', { import: 'default' });

export function loadYearSongs(year: number): Promise<YearSongs> {
  const load = songLoaders[`./songs/${year}.json`];
  if (!load) return Promise.reject(new Error(`No song data for ${year}`));
  return load();
}

/**
 * Weighted random draw without replacement: each pick is chosen with probability
 * weight / (total weight still in the pool). Never returns more songs than the pool holds.
 * `random` is injectable for tests or reproducible playlists.
 */
export function drawSongs(pool: PoolSong[], n: number, random: () => number = Math.random): PoolSong[] {
  const left = [...pool];
  const picked: PoolSong[] = [];
  while (picked.length < n && left.length > 0) {
    const total = left.reduce((sum, song) => sum + song.weight, 0);
    let r = random() * total;
    let i = 0;
    for (; i < left.length - 1; i++) {
      r -= left[i].weight;
      if (r < 0) break;
    }
    picked.push(left.splice(i, 1)[0]);
  }
  return picked;
}

/** Draws `perBand` songs for each distinct band picked, in the order the sets start. */
export async function buildPlaylist(
  year: number,
  chosen: SetTime[],
  perBand: number,
  random: () => number = Math.random,
): Promise<Playlist> {
  const songs = await loadYearSongs(year);
  const ordered = [...chosen].sort((a, b) => a.startTime.localeCompare(b.startTime));
  const tracks: PlaylistTrack[] = [];
  const noSongs: string[] = [];
  for (const band of new Set(ordered.map((set) => set.band))) {
    const entry = songs.bands[band];
    if (!entry) {
      noSongs.push(band);
      continue;
    }
    for (const song of drawSongs(entry.pool, perBand, random)) {
      tracks.push({ band, artist: song.artist ?? band, title: song.title, year: song.year });
    }
  }
  return { year, tracks, noSongs };
}

/** Plain-text lines for logging a playlist. */
export function formatPlaylist(playlist: Playlist): string[] {
  const lines = [`Warped Tour ${playlist.year} playlist: ${playlist.tracks.length} songs`];
  playlist.tracks.forEach((track, i) => {
    lines.push(`${String(i + 1).padStart(2)}. ${track.artist} - ${track.title} (${track.year})`);
  });
  if (playlist.noSongs.length) lines.push(`No song data: ${playlist.noSongs.join(', ')}`);
  return lines;
}
